In [121]:
import numpy as np
print(np.__version__) 

1.21.5


In [122]:
#  doubts here
arr=np.array(10)
print(arr)
print(type(arr))
arr

10
<class 'numpy.ndarray'>


array(10)

In [123]:
arr=np.array([15,11])
print(arr)
arr

[15 11]


array([15, 11])

In [124]:
arr=np.array([[2,3],[4,5]])
print(arr)

[[2 3]
 [4 5]]


Arrays in numpy in all dimesnsions  

In [125]:
import numpy as np
print(np.array([10]),np.array(20)) # 0 d
print(np.array([1,2])) # 1 d
print(np.array([[1,2],[3,4]]))  # 2 d
print(np.array([[[1,2,3,4,6],[3,4,3,5,6]]])) # 3 d

[10] 20
[1 2]
[[1 2]
 [3 4]]
[[[1 2 3 4 6]
  [3 4 3 5 6]]]


ndmin = 5

In [126]:
arr=np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[4,6,8,2,0]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 4  6  8  2  0]]]
3
(3, 1, 5)


In [127]:
arr=np.array((1,2,3,4),ndmin=3)
print(arr)
print(arr.ndim) #gives dimension of array

[[[1 2 3 4]]]
3


filling arrays with zeros

In [128]:
import numpy  as np
arr= np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [129]:
arr=np.ones((4,2,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [130]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

 below code : arange stands for array range, range functions applicable

In [131]:
arr=np.arange(10)
arr
np.arange(4)

array([0, 1, 2, 3])

In [132]:
arr=np.arange(10,21,2)
arr

array([10, 12, 14, 16, 18, 20])

sorting arrays numbers and alphabets

In [133]:
import numpy as np
arr=np.array([8,7,6,5,4,3,2,1])
sorted_array=np.sort(arr)
print(arr, sorted_array)


[8 7 6 5 4 3 2 1] [1 2 3 4 5 6 7 8]


In [134]:
arr=np.array(["tea","apple","zebra"])
sorted_array=np.sort(arr)
print(sorted_array)

['apple' 'tea' 'zebra']


sorting 2d array

In [135]:
arr=np.array([[5,2,1],[3,2,1]])
sorted_array=np.sort(arr)
print(sorted_array)

[[1 2 5]
 [1 2 3]]


access array elements

In [136]:
arr=np.array([1,2,3,4,5,6])
print(arr[-5:-1:])
print(arr[2]) # indexing
print(arr[3:5])# slicing

[2 3 4 5]
3
[4 5]


In [137]:
# mat=np.array([[10,20,22,24,25],[30,40,45,48,56]])
# print(mat)
# print(mat[0,1])
mat=np.array([[[1,2,3,4,5,6]],[[6,5,4,3,2,1]]])
print(mat[1,0,1])


5


In [138]:
mat=np.array([  [[1,2,3],[4,5,6]] , [[2,3,4],[3,4,5]]  ])
# print(mat)
print(mat[1,1,2])
print(mat[1,1,1:3])

5
[4 5]


In [139]:
arr=np.array([2,80,40,60,40])
value=np.where(arr==60)
print(value)
arr1=np.array(["a","d","f","g"])
value1=np.where(arr1=="d")
value1



(array([3], dtype=int64),)


(array([1], dtype=int64),)

In [140]:
arr=np.array([2,80,40,60,40])
value2=np.array(arr%4==0)
value2

array([False,  True,  True,  True,  True])

searchsorted()

In [141]:
arr=np.array([1,2,3,4,5])
val=np.searchsorted(arr,3)
print(arr)
val


[1 2 3 4 5]


2

In [142]:
arr=np.array([1,2,3,4])


reshaping an array reshape()

In [143]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

oldarr=newarr.reshape(-1)
oldarr 
# increase and decrease the order of the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
import numpy as np 
arr=np.array([10,20,30,40,50,60,70])
b=[True,False,True,True,False,False,True]
newarr=arr[b]
print(newarr)

[10 30 40 70]


In [145]:
arr=np.array([0,1,2,3,5,8,13])
result=filter(lambda x:x%2!=0,arr)
print(result)
print(list(result))
result

[1, 3, 5, 13]


In [146]:
# concatenation of arrays
a=np.arange(6).reshape(2,3)
print(a)
b=np.arange(7,13).reshape(2,3)
print(b)
c=np.arange(20,32).reshape(4,3)
d=np.concatenate((a,b,c))
print("conctaenated\n",d)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
conctaenated
 [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


In [147]:
e=np.concatenate((a,b),axis=1)# horizontal addition 
f=np.concatenate((a,b),axis=0)# vertical addition
print(e)
f


[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [148]:
g=np.stack((a,b),axis=0)
h=np.stack((a,b),axis=1)
i=np.stack((a,b),axis=2)
print(a)
print(b)
print(g)
print(h)
print(i)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 0  1  2]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 11 12]]]
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [149]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [150]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [151]:
mat=np.dstack((a,b))
print(mat[1,2,1]) # chooses the position of value, first matrix , then row, then column
print(mat)

12
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [154]:
c=np.arange(4,10).reshape(2,3)
print(np.hstack((a,b,c)))
print(np.dstack((a,b,c)))
print(np.vstack((a,b,c)))



[[ 0  1  2  7  8  9  4  5  6]
 [ 3  4  5 10 11 12  7  8  9]]
[[[ 0  7  4]
  [ 1  8  5]
  [ 2  9  6]]

 [[ 3 10  7]
  [ 4 11  8]
  [ 5 12  9]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


pandas

In [155]:
import pandas as pd
l=[10,20,30,40,50]

S=pd.Series(data=l)
print(S)

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

In [ ]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s=pd.Series((a))
s

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

In [ ]:
s=pd.Series(a,index("a","b","c","d","e","f","g","h","i"))
print(s)
print(['c'])


NameError: name 'pd' is not defined

In [ ]:
l1=[1,2,3,4]
a=pd.Series(l1)
a

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
df=pd.read_json("C:/Users/User4/Desktop/numpy.module/data.json")
df

students
student1  {'name': 'ABC', 'rollnumber': 1, 'class': 1, '...
student2       {'name': 'DEF', 'rollnumber': 2, 'class': 2}
student3       {'name': 'EFG', 'rollnumber': 3, 'class': 3}

In [ ]:
{
    "students":
    {
        "student1":
        {
            "name":"ABC",
            "rollnumber":1,
            "class":1,
            "phones":{
                "num1":"+910000000000",
                "num2":"+910000000000"
            }
        },
        "student2":
        {
            "name":"DEF",
            "rollnumber":2,
            "class":2
        },
        "student3":
        {
            "name":"EFG",
            "rollnumber":3,
            "class":3
        }
    }
}