In [1]:
import numpy as np
print(np.__version__) 

1.24.1


In [2]:
#  doubts here
arr=np.array(10)
print(arr)
print(type(arr))
arr

10
<class 'numpy.ndarray'>


array(10)

In [8]:
l=[15,11]
arr=np.array([10,20])
print(arr)
print(type(arr),type(l))
arr

[10 20]
<class 'numpy.ndarray'> <class 'list'>


array([10, 20])

In [11]:
# creating 0 dimension array
arr=np.array(20)
print(arr)
arr

20


array(20)

In [1]:
# creating 1D array
arr=np.array([1,2,3,4])
mean=np.mean(arr)
print(arr)
mean

NameError: name 'np' is not defined

In [21]:
# creating a 2D array
l=[[2,3,6],[4,5,2]]
m=[[2,3],[4,2]]
arr=np.array(l)
print(arr)
arr

[[2 3 6]
 [4 5 2]]


array([[2, 3, 6],
       [4, 5, 2]])

In [41]:
# creating a 3D array

arr=np.array([[[1,3,2],[1,2,3]],[[2,4,6],[2,1,4]]])
arr

array([[[1, 3, 2],
        [1, 2, 3]],

       [[2, 4, 6],
        [2, 1, 4]]])

Arrays in numpy in all dimesnsions  

In [30]:
#  creating multidimensional arrays
import numpy as np
print(np.array([10]),np.array(20)) # 0 d
print(np.array([1,2])) # 1 d
print(np.array([[1,2],[3,4]]))  # 2 d
print(np.array([[[1,2,3,4,6],[3,4,3,5,6]]])) # 3 d


[10] 20
[1 2]
[[1 2]
 [3 4]]
[[[1 2 3 4 6]
  [3 4 3 5 6]]]


In [67]:
#  creating array of 5D
arr=np.array([1,2,5,6,4],ndmin=5)
print(arr.shape)
arr

(1, 1, 1, 1, 5)


array([[[[[1, 2, 5, 6, 4]]]]])

ndmin = 5

In [68]:
# chexking the shape and dimensions
arr=np.array([[[1,2,3,4,5]],[[6,7,8,9,10]],[[4,6,8,2,0]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[ 4  6  8  2  0]]]
3
(3, 1, 5)


In [105]:
arr=np.array((1,2,3,4),ndmin=3)
print(arr)
print(arr.ndim) #gives dimension of array

[[[1 2 3 4]]]
3


filling arrays with zeros

In [99]:
import numpy  as np
arr= np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [100]:
arr=np.ones((2,1,3),dtype=int) # read as 2 matrices of 1 row and 3 coloumns
print(arr)


[[[1 1 1]]

 [[1 1 1]]]


In [97]:
arr=np.ones((1,3,2))
arr

array([[1., 1., 1.]])

 below code : arange stands for array range, range functions applicable

In [101]:
arr=np.arange(10)
arr
# np.arange(4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
arr=np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

sorting arrays numbers and alphabets

In [111]:
import numpy as np
arr=np.array([8,7,6,5,4,3,2,1])
sorted_array=np.sort(arr)
print(arr, sorted_array)


[8 7 6 5 4 3 2 1] [1 2 3 4 5 6 7 8]


In [112]:
arr=np.array(["tea","apple","zebra"])
sorted_array=np.sort(arr)
print(sorted_array)

['apple' 'tea' 'zebra']


sorting 2d array

In [113]:
arr=np.array([[5,2,1],[3,2,1]])
sorted_array=np.sort(arr)
print(sorted_array)

[[1 2 5]
 [1 2 3]]


access array elements

In [109]:
arr=np.array([1,2,3,4,5,6])
print(arr[-5:-1:])
print(arr[2]) # indexing
print(arr[3:5])# slicing



[2 3 4 5]
3
[4 5]


In [122]:
mat=np.array([[10,20,22,24,25],[30,40,45,48,56]])
print(mat)
print(mat[0,1])
mat=np.array([[[1,2,3,4,5,6]],[[6,5,4,3,2,1]]])
print(mat[1,0,2])


[[10 20 22 24 25]
 [30 40 45 48 56]]
20
4


In [116]:
mat=np.array([  [[1,2,3],[4,5,6]] , [[2,3,4],[3,4,5]]  ])
# print(mat)
print(mat[1,1,2])
print(mat[1,1,1:3])

5
[4 5]


In [117]:
arr=np.array([2,80,40,60,40])
value=np.where(arr==60)
print(value)
arr1=np.array(["a","d","f","g"])
value1=np.where(arr1=="d")
value1



(array([3], dtype=int64),)


(array([1], dtype=int64),)

In [118]:
arr=np.array([2,80,40,60,40])
value2=np.array(arr%4==0)
value2

array([False,  True,  True,  True,  True])

searchsorted()

In [119]:
arr=np.array([1,2,3,4,5])
val=np.searchsorted(arr,3)
print(arr)
val


[1 2 3 4 5]


2

In [120]:
arr=np.array([1,2,3,4])


reshaping an array reshape()

In [121]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4)
print(newarr)

oldarr=newarr.reshape(-1)
oldarr 
# increase and decrease the order of the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [122]:
import numpy as np 
arr=np.array([10,20,30,40,50,60,70])
b=[True,False,True,True,False,False,True]
newarr=arr[b]
print(newarr)

[10 30 40 70]


In [123]:
arr=np.array([0,1,2,3,5,8,13])
result=filter(lambda x:x%2!=0,arr)
print(result)
print(list(result))
result

TypeError: 'list' object is not callable

In [ ]:
# concatenation of arrays
a=np.arange(6).reshape(2,3)
print(a)
b=np.arange(7,13).reshape(2,3)
print(b)
c=np.arange(20,32).reshape(4,3)
d=np.concatenate((a,b,c))
print("conctaenated\n",d)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
conctaenated
 [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


In [ ]:
e=np.concatenate((a,b),axis=1)# horizontal addition 
f=np.concatenate((a,b),axis=0)# vertical addition
print(e)
f


[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
g=np.stack((a,b),axis=0)
h=np.stack((a,b),axis=1)
i=np.stack((a,b),axis=2)
print(a)
print(b)
print(g)
print(h)
print(i)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 0  1  2]
  [ 7  8  9]]

 [[ 3  4  5]
  [10 11 12]]]
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [ ]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [ ]:
mat=np.dstack((a,b))
print(mat[1,2,1]) # chooses the position of value, first matrix , then row, then column
print(mat)

12
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [ ]:
c=np.arange(4,10).reshape(2,3)
print(np.hstack((a,b,c)))
print(np.dstack((a,b,c)))
print(np.vstack((a,b,c)))



[[ 0  1  2  7  8  9  4  5  6]
 [ 3  4  5 10 11 12  7  8  9]]
[[[ 0  7  4]
  [ 1  8  5]
  [ 2  9  6]]

 [[ 3 10  7]
  [ 4 11  8]
  [ 5 12  9]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


pandas

In [ ]:
import pandas as pd
l=[10,20,30,40,50,60,70]

S=pd.Series(data=l)

print(S)


In [ ]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
s=pd.Series((a))
s

In [ ]:
#  creating a series using a list 
import numpy as np
list=[1,4,7,8,5,4,2]
ser=pd.Series(list,index=[1,2,3,4,5,6,7])
ser

In [ ]:
#  creating empty series
import pandas as pd
ser=pd.Series()
ser

In [144]:
# creating  a series using dictionary
import pandas as  pd
dict={"a":1,2:2,6:{1:"l"},6:4}
ser=pd.Series(dict)
ser


a    1
2    2
6    4
dtype: int64

In [ ]:
# creating series from scalar value
import pandas as pd
ser=pd.Series(10,index=[0,1,2,3,4])
ser

In [ ]:
# creating series using numpy functions
import pandas as pd
import numpy as np
ser1=pd.Series(np.linspace(3,4,11))
print(ser1)
ser2=pd.Series(np.linspace(1, 100, 10))
print(ser2)
# print();

In [ ]:
# creating a series from range function
import pandas as pd
a=pd.Series(range(5))
a

In [ ]:
#  creating a series using for loop and its comprehension
import pandas as pd
a=pd.Series(range(1,14,3),index=[x for x in "abcde"])
a

In [ ]:
#  creating a series using mathmatical function
import pandas as pd
import numpy as np
ser=np.arange(5,10)
ser1=pd.Series(data=ser*5,index=ser)
ser1

In [ ]:
# accessing elements of series
import pandas as pd
import numpy as np

data=np.array([2,5,8,1,4,7,9,6,3,2,5,4,6,9,8,7])
ser=pd.Series(data)
print(ser[:5])
#  accessing element using Label(index)
print(ser[6])



In [135]:
s=pd.Series(a,index("a","b","c","d","e","f","g","h","i"))
print(s)
print(['c'])


NameError: name 'index' is not defined

In [3]:
# l1=[1,2,3,4]
# a=pd.Series(l1)
# a


NameError: name 'data' is not defined

In [1]:
import pandas as pd
df=pd.read_json("C:/Users/User4/Desktop/numpy.module/data.json")
# print(df.to_string())
print(df.head())
print(df.tail())

# print(df.shape)
print(df.loc())
# df[2:1:1]


                                                   students
student1  {'name': 'ABC', 'rollnumber': 1, 'class': 1, '...
student2  {'name': 'DEF', 'rollnumber': 2, 'class': 2, '...
student3  {'name': 'EFG', 'rollnumber': 3, 'class': 3, '...
student4  {'name': 'HIJ', 'rollnumber': 4, 'class': 4, '...
student5  {'name': 'jkl', 'rollnumber': 5, 'class': 5, '...
                                                   students
student2  {'name': 'DEF', 'rollnumber': 2, 'class': 2, '...
student3  {'name': 'EFG', 'rollnumber': 3, 'class': 3, '...
student4  {'name': 'HIJ', 'rollnumber': 4, 'class': 4, '...
student5  {'name': 'jkl', 'rollnumber': 5, 'class': 5, '...
student6  {'name': 'lmn', 'rollnumber': 6, 'class': 6, '...


In [105]:
df.loc(1)

In [7]:
{
    "students":
    {
        "student1":
        {
            "name":"ABC",
            "rollnumber":1,
            "class":1,
            "phones":{
                "num1":"+910000000000",
                "num2":"+910000000000"
            }
        },
        "student2":
        {
            "name":"DEF",
            "rollnumber":2,
            "class":2
        },
        "student3":
        {
            "name":"EFG",
            "rollnumber":3,
            "class":3
        }
    }
}

{'students': {'student1': {'name': 'ABC',
   'rollnumber': 1,
   'class': 1,
   'phones': {'num1': '+910000000000', 'num2': '+910000000000'}},
  'student2': {'name': 'DEF', 'rollnumber': 2, 'class': 2},
  'student3': {'name': 'EFG', 'rollnumber': 3, 'class': 3}}}